name: Installing + Caching python and the requirements 

on:
  push:
    branches:
      - main  # Runs on push to the main branch
  schedule:
    - cron: '0 * * * *'  # Runs every hour

  workflow_dispatch: # Allows manual triggering of the workflow. Helps is debugging.

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    
    - name: Check Disk Usage Before Cleanup
      run: |
        echo "Disk space before cleanup:"
        df -h  # Show disk usage
        echo "Top 20 largest directories:"
        sudo du -ah / | sort -rh | head -20  # Show top 20 biggest directories
    
    - name: Clean Up Disk Space
      run: |
        echo "Cleaning up disk space..."
    
        echo "Removing unnecessary packages and logs..."
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        
        echo "Clearing cached files..."
        sudo rm -rf ~/.cache/*
        sudo rm -rf /tmp/*
        
        echo "Removing Docker images (if applicable)..."
        docker system prune -a -f  # Removes unused Docker images, networks, and containers
    
        echo "Checking large files in /usr and /var..."
        sudo du -sh /usr /var  # Shows total size of /usr and /var
    
        echo "Checking disk space after cleanup..."
        df -h  # Check available disk space

        
    - name: Configure Git user
      run: |
        git config --global user.name "krishangguptafibonacciresearch"  # Replace with your name
        git config --global user.email "krishanggupta@fibonacciresearch.in"  # Replace with your email

    - name: Pull latest changes to integrate remote updates
      run: |
        git pull origin main || echo "No changes to pull"

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        

