name: V2_Daily Python Script Run

on:
  push:
    branches:
      - V2_updates_every_hr  # Specify branches to monitor for push events (adjust as needed)
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  run-python:
    if: github.ref == 'refs/heads/V2_updates_every_hr'  # Ensures the job runs only for the V2 branch
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3  # Use v3 for the latest version

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'  # Use the specific version of Python you need

    - name: Install dependencies manually
      run: |
        pip install pandas
        pip install numpy
        pip install matplotlib
        pip install yfinance
        pip install seaborn
        
    - name: Run Python script
      run: python periodic_runner_main.py  # Replace with your actual Python script name

    - name: Configure Git user
      run: |
        git config --global user.name "krishangguptafibonacciresearch"  # Replace with your name
        git config --global user.email "krishanggupta@fibonacciresearch.in"  # Replace with your email

    - name: Check if both folders have files and commit changes
      run: |
        # Check if  folders exist and contain files
        if [ -d "Intraday_data_files" ] && [ "$(ls -A Intraday_data_files)" ]; then
          echo "Folders with files detected, committing changes"
          git add .
          git commit -m "Add new folders and files created by Python script"
          git push
        else
          echo "Folders do not have files, skipping commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
